sudo: required
dist: trusty
language: cpp
compiler:
- gcc
cache: apt
git:
  depth: 5
before_install:
- sudo apt update -qq
- sudo apt -y install -qq devscripts equivs lintian qt5-default
- mk-build-deps -i -s sudo -t "apt --yes --no-install-recommends"
- dpkg -l | grep qt
script: debuild --preserve-env --preserve-envvar PATH -i -us -uc -b
after_success:
- sudo dpkg -i ../gcoder*.deb
- sudo apt -y -f install
- lintian -i ../gcoder*.dsc
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d98e263cc11c95bbb2c4
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
