sudo: required
dist: trusty
language: cpp
compiler:
- gcc
cache: apt
before_install:
- sudo apt update -qq
- sudo apt -y install -qq devscripts equivs lintian qt5-default
- mk-build-deps -i -s sudo -t "apt --yes --no-install-recommends"
- dpkg -l | grep qt
script: debuild --preserve-env --preserve-envvar PATH -i -us -uc -b
after_success:
- sudo dpkg -i ../gcoder*.deb
- sudo apt -y -f install
- lintian -i ../gcoder*.dsc
notifications:
  email: false
  irc:
    channels:
    - irc.freenode.org#gcoder
    use_notice: true
